server:
  port: 7001

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver  # MariaDB 전용 드라이버
    url: jdbc:mariadb://localhost:3307/springcqrs  # 컨테이너 내에서 mariaDB 서비스 이름 사용
    username: root
    password: ys1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect  # MariaDB 전용 dialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: youaresoft
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer